trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-pr.yml
    - .azure-pipelines/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - AzurePipelineSample.NETStandard.Lib/*
    - AzurePipelineSample.NETStandard.Lib.Test/*
    - AzurePipelineSample.NETCore.Console/*
    - AzurePipelineSample.NETCore.Console.Test/*
    - AzurePipelineSample.NETStandard.Core/*
    - AzurePipelineSample.NETStandard.Core.Test/*
    - azure-pipelines-pr.yml
    - .azure-pipelines/*

variables:
  - template: .azure-pipelines/variables.yml

stages:
- stage: Build
  variables:
    buildOnPR: $[not(eq(variables['Build.Reason'], 'PullRequest'))]
    pipelineChanged: $[dependencies.Check_PR_Diff.outputs['diff.PipelineChanged']]
    libChanged: $[dependencies.Check_PR_Diff.outputs['diff.LibChanged']]
    coreChanged: $[dependencies.Check_PR_Diff.outputs['diff.CoreChanged']]
    consoleChanged: $[dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged']]
  jobs:
  - template: .azure-pipelines/diff_variables.yml
    parameters:
      jobName: 'Check_PR_Diff'
      jobDisplayName: 'Check PR Diff'
      pipelineFile: 'azure-pipelines-pr.yml'
  - template: .azure-pipelines/build-lib.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(variables['buildOnPR'],'True'),
          eq(variables['pipelineChanged'],'True'),
          eq(variables['libChanged'],'True'),
          eq(variables['coreChanged'],'True'),
          eq(variables['consoleChanged'],'True')
        )
  - template: .azure-pipelines/build-lib-test.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Lib'),
          or(
            eq(variables['buildOnPR'],'True'),
            eq(variables['pipelineChanged'],'True'), 
            eq(variables['libChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-core.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Lib'),
          or(
            eq(variables['buildOnPR'],'True'),
            eq(variables['pipelineChanged'],'True'), 
            eq(variables['libChanged'],'True'),
            eq(variables['coreChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-core-test.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Core'),
          or(
            eq(variables['buildOnPR'],'True'),
            eq(variables['pipelineChanged'],'True'),
            eq(variables['coreChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-console.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Core'),
          or(
            eq(variables['buildOnPR'],'True'),
            eq(variables['pipelineChanged'],'True'), 
            eq(variables['libChanged'],'True'),
            eq(variables['coreChanged'],'True'),
            eq(variables['consoleChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-console-test.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Console'),
          or(
            eq(variables['buildOnPR'],'True'),
            eq(variables['pipelineChanged'],'True'),
            eq(variables['consoleChanged'],'True')
          )
        )

- stage: Test
  dependsOn: Build
  variables:
    buildOnPR: $[not(eq(variables['Build.Reason'], 'PullRequest'))]
    pipelineChanged: $[dependencies.Check_PR_Diff.outputs['diff.PipelineChanged']]
    libChanged: $[dependencies.Check_PR_Diff.outputs['diff.LibChanged']]
    coreChanged: $[dependencies.Check_PR_Diff.outputs['diff.CoreChanged']]
    consoleChanged: $[dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged']]
  jobs:
  - template: .azure-pipelines/diff_variables.yml
    parameters:
      jobName: 'Check_PR_Diff'
      jobDisplayName: 'Check PR Diff'
      pipelineFile: 'azure-pipelines-pr.yml'
  - template: .azure-pipelines/test-lib.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(variables['buildOnPR'],'True'),
          eq(variables['pipelineChanged'],'True'), 
          eq(variables['libChanged'],'True')
        )
  - template: .azure-pipelines/test-core.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(variables['buildOnPR'],'True'),
          eq(variables['pipelineChanged'],'True'), 
          eq(variables['coreChanged'],'True')
        )
  - template: .azure-pipelines/test-console.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(variables['buildOnPR'],'True'),
          eq(variables['pipelineChanged'],'True'), 
          eq(variables['consoleChanged'],'True')
        )