trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-pr-lib.yml
    - .azure-pipelines/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - AzurePipelineSample.NETCore.Console/*
    - AzurePipelineSample.NETCore.Console.Test/*
    - azure-pipelines-pr-console.yml
    - .azure-pipelines/*

variables:
  buildConfiguration: 'CI_Release'
  libProject: 'AzurePipelineSample.NETStandard.Lib'
  libBinaryDirectory: '$(libProject)/bin/$(buildConfiguration)/netstandard2.0'
  libTestProject: 'AzurePipelineSample.NETStandard.Lib.Test'
  libTestBinaryDirectory: '$(libTestProject)/bin/$(buildConfiguration)/netcoreapp2.1'
  coreProject: 'AzurePipelineSample.NETStandard.Core'
  coreBinaryDirectory: '$(coreProject)/bin/$(buildConfiguration)/netstandard2.0'
  coreTestProject: 'AzurePipelineSample.NETStandard.Core.Test'
  coreTestBinaryDirectory: '$(coreTestProject)/bin/$(buildConfiguration)/netcoreapp2.1'
  consoleProject: 'AzurePipelineSample.NETCore.Console'
  consoleBinaryDirectory: '$(consoleProject)/bin/$(buildConfiguration)/netcoreapp2.1'
  consoleTestProject: 'AzurePipelineSample.NETCore.Console.Test'
  consoleTestBinaryDirectory: '$(consoleTestProject)/bin/$(buildConfiguration)/netcoreapp2.1'

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/build-lib.yml
　- template: .azure-pipelines/build-core.yml
  - template: .azure-pipelines/build-console.yml
  - template: .azure-pipelines/build-console-test.yml
- stage: Test
  dependsOn: Build
  jobs:
  - template: .azure-pipelines/test-console.yml