trigger:
- master

pr: none

variables:
  - template: .azure-pipelines/variables.yml

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/build-lib.yml
  - template: .azure-pipelines/build-lib-test.yml
  - template: .azure-pipelines/build-core.yml
  - template: .azure-pipelines/build-core-test.yml
  - template: .azure-pipelines/build-console.yml
  - template: .azure-pipelines/build-console-test.yml
- stage: Test
  dependsOn: Build
  jobs:
  - template: .azure-pipelines/test-lib.yml
  - template: .azure-pipelines/test-core.yml
  - template: .azure-pipelines/test-console.yml