trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-pr.yml
    - .azure-pipelines/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - AzurePipelineSample.NETStandard.Lib/*
    - AzurePipelineSample.NETStandard.Lib.Test/*
    - AzurePipelineSample.NETCore.Console/*
    - AzurePipelineSample.NETCore.Console.Test/*
    - AzurePipelineSample.NETStandard.Core/*
    - AzurePipelineSample.NETStandard.Core.Test/*
    - azure-pipelines-pr.yml
    - .azure-pipelines/*

variables:
  - template: .azure-pipelines/variables.yml

stages:
- stage: Build
  variables:
    buildOnPR: $[not(eq(variables['Build.Reason'], 'PullRequest'))]
    pipelineChanged: $[dependencies.Check_PR_Diff.outputs['diff.PipelineChanged']]
    libChanged: $[dependencies.Check_PR_Diff.outputs['diff.LibChanged']]
    coreChanged: $[dependencies.Check_PR_Diff.outputs['diff.CoreChanged']]
    consoleChanged: $[dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged']]
  jobs:
  - template: .azure-pipelines/diff_variables.yml
    parameters:
      jobName: 'Check_PR_Diff'
      jobDisplayName: 'Check PR Diff'
      pipelineFile: 'azure-pipelines-pr.yml'
  - template: .azure-pipelines/build-lib.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: $[or(buildOnPR, pipelineChanged, libChanged, coreChanged, consoleChanged)]
  - template: .azure-pipelines/build-lib-test.yml
    parameters:
      condition: |
        and(
          succeeded('Build_Lib'),
          or(
            not(eq(variables['Build.Reason'], 'PullRequest')),
            dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'], 
            dependencies.Check_PR_Diff.outputs['diff.LibChanged']
          )
        )
  - template: .azure-pipelines/build-core.yml
    parameters:
      condition: |
        and(
          succeeded('Build_Lib'),
          or(
            not(eq(variables['Build.Reason'], 'PullRequest')),
            dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'], 
            dependencies.Check_PR_Diff.outputs['diff.LibChanged'],
            dependencies.Check_PR_Diff.outputs['diff.CoreChanged']
          )
        )
  - template: .azure-pipelines/build-core-test.yml
    parameters:
      condition: |
        and(
          succeeded('Build_Core'),
          or(
            not(eq(variables['Build.Reason'], 'PullRequest')),
            dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],
            dependencies.Check_PR_Diff.outputs['diff.CoreChanged']
          )
        )
  - template: .azure-pipelines/build-console.yml
    parameters:
      condition: |
        and(
          succeeded('Build_Core'),
          or(
            not(eq(variables['Build.Reason'], 'PullRequest')),
            dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'], 
            dependencies.Check_PR_Diff.outputs['diff.LibChanged'],
            dependencies.Check_PR_Diff.outputs['diff.CoreChanged'],
            dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged']
          )
        )
  - template: .azure-pipelines/build-console-test.yml
    parameters:
      condition: |
        and(
          succeeded('Build_Console'),
          or(
            not(eq(variables['Build.Reason'], 'PullRequest')),
            dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],
            dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged']
          )
        )

- stage: Test
  dependsOn: Build
  jobs:
  - template: .azure-pipelines/diff_variables.yml
    parameters:
      jobName: 'Check_PR_Diff'
      jobDisplayName: 'Check PR Diff'
      pipelineFile: 'azure-pipelines-pr.yml'
  - template: .azure-pipelines/test-lib.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          not(eq(variables['Build.Reason'], 'PullRequest')),
          dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'], 
          dependencies.Check_PR_Diff.outputs['diff.LibChanged']
        )
  - template: .azure-pipelines/test-core.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          not(eq(variables['Build.Reason'], 'PullRequest')),
          dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'], 
          dependencies.Check_PR_Diff.outputs['diff.CoreChanged']
        )
  - template: .azure-pipelines/test-console.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          not(eq(variables['Build.Reason'], 'PullRequest')),
          dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'], 
          dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged']
        )