trigger: none

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - AzurePipelineSample.NETStandard.Core/*
    - AzurePipelineSample.NETStandard.Core.Test/*
    - AzurePipelineSample.NETCore.Console/*
    - AzurePipelineSample.NETCore.Console.Test/*
    include:
    - AzurePipelineSample.NETStandard.Lib/*
    - AzurePipelineSample.NETStandard.Lib.Test/*

variables:
  buildConfiguration: 'CI_Release'
  libProject: 'AzurePipelineSample.NETStandard.Lib'
  libBinaryDirectory: '$(libProject)/bin/$(buildConfiguration)/netstandard2.0'
  libTestProject: 'AzurePipelineSample.NETStandard.Lib.Test'
  libTestBinaryDirectory: '$(libTestProject)/bin/$(buildConfiguration)/netcoreapp2.1'
  coreProject: 'AzurePipelineSample.NETStandard.Core'

stages:
- stage: Build
  jobs:
  - job: Build_Lib
    displayName: Lib
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'build $(buildConfiguration)'
      inputs:
        command: 'build'
        projects: '$(libProject)/*.csproj'
        arguments: '-c $(buildConfiguration)'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'libBinary'
        targetPath: '$(libBinaryDirectory)'

  - job: Build_Lib_Test
    displayName: Lib Test
    dependsOn: Build_Lib
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'libBinary'
        targetPath: '$(libBinaryDirectory)'
    - script: 'dotnet publish $(libTestProject)/$(libTestProject).csproj -c $(buildConfiguration)'
      displayName: 'build $(buildConfiguration)'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'libTestBinary'
        targetPath: '$(libTestBinaryDirectory)'

  - job: Build_Core
    displayName: Core
    dependsOn: Build_Lib
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'libBinary'
        targetPath: '$(libBinaryDirectory)'
    - task: DotNetCoreCLI@2
      displayName: 'build $(buildConfiguration)'
      inputs:
        command: 'build'
        projects: '$(coreProject)/*.csproj'
        arguments: '-c $(buildConfiguration)'


- stage: Test
  dependsOn: Build
  jobs:
  - job: Test_Lib
    displayName: Lib
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'libTestBinary'
        targetPath: '$(libTestBinaryDirectory)'
    - script: 'dotnet vstest $(System.DefaultWorkingDirectory)/$(libTestBinaryDirectory)/publish/$(libTestProject).dll /logger:trx /ResultsDirectory:$(System.DefaultWorkingDirectory)/Results'
      displayName: Run Test
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'