trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-pr-lib.yml
    - .azure-pipelines/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - AzurePipelineSample.NETCore.Console/*
    - AzurePipelineSample.NETCore.Console.Test/*
    - azure-pipelines-pr-console.yml
    - .azure-pipelines/*

variables:
  - template: .azure-pipelines/variables.yml

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/build-lib.yml
  - template: .azure-pipelines/build-core.yml
  - template: .azure-pipelines/build-console.yml
  - template: .azure-pipelines/build-console-test.yml
- stage: Test
  dependsOn: Build
  jobs:
  - template: .azure-pipelines/test-console.yml