trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-pr-lib.yml
    - .azure-pipelines/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - AzurePipelineSample.NETStandard.Lib/*
    - AzurePipelineSample.NETStandard.Lib.Test/*
    - azure-pipelines-pr-lib.yml
    - .azure-pipelines/*

variables:
  - template: .azure-pipelines/variables.yml

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/build-lib.yml
  - template: .azure-pipelines/build-lib-test.yml
  - template: .azure-pipelines/build-core.yml
- stage: Test
  dependsOn: Build
  jobs:
  - template: .azure-pipelines/test-lib.yml