trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-pr.yml
    - .azure-pipelines/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - AzurePipelineSample.NETStandard.Lib/*
    - AzurePipelineSample.NETStandard.Lib.Test/*
    - AzurePipelineSample.NETCore.Console/*
    - AzurePipelineSample.NETCore.Console.Test/*
    - AzurePipelineSample.NETStandard.Core/*
    - AzurePipelineSample.NETStandard.Core.Test/*
    - azure-pipelines-pr.yml
    - .azure-pipelines/*

variables:
  - template: .azure-pipelines/variables.yml

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/diff_variables.yml
    parameters:
      jobName: 'Check_PR_Diff'
      jobDisplayName: 'Check PR Diff'
      pipelineFile: 'azure-pipelines-pr.yml'
  - template: .azure-pipelines/build-lib.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
          eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'),
          eq(dependencies.Check_PR_Diff.outputs['diff.LibChanged'],'True'),
          eq(dependencies.Check_PR_Diff.outputs['diff.CoreChanged'],'True'),
          eq(dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged'],'True')
        )
  - template: .azure-pipelines/build-lib-test.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Lib'),
          or(
            eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'), 
            eq(dependencies.Check_PR_Diff.outputs['diff.LibChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-core.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Lib'),
          or(
            eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'), 
            eq(dependencies.Check_PR_Diff.outputs['diff.LibChanged'],'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.CoreChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-core-test.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Core'),
          or(
            eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.CoreChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-console.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Core'),
          or(
            eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'), 
            eq(dependencies.Check_PR_Diff.outputs['diff.LibChanged'],'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.CoreChanged'],'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged'],'True')
          )
        )
  - template: .azure-pipelines/build-console-test.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        and(
          succeeded('Build_Console'),
          or(
            eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'),
            eq(dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged'],'True')
          )
        )

- stage: Test
  dependsOn: Build
  jobs:
  - template: .azure-pipelines/diff_variables.yml
    parameters:
      jobName: 'Check_PR_Diff'
      jobDisplayName: 'Check PR Diff'
      pipelineFile: 'azure-pipelines-pr.yml'
  - template: .azure-pipelines/test-lib.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
          eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'), 
          eq(dependencies.Check_PR_Diff.outputs['diff.LibChanged'],'True')
        )
  - template: .azure-pipelines/test-core.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
          eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'), 
          eq(dependencies.Check_PR_Diff.outputs['diff.CoreChanged'],'True')
        )
  - template: .azure-pipelines/test-console.yml
    parameters:
      dependsOn: 'Check_PR_Diff'
      condition: |
        or(
          eq(not(eq(variables['Build.Reason'], 'PullRequest')),'True'),
          eq(dependencies.Check_PR_Diff.outputs['diff.PipelineChanged'],'True'), 
          eq(dependencies.Check_PR_Diff.outputs['diff.ConsoleChanged'],'True')
        )