trigger: 
- master

stages:
  - stage: Stage1
    jobs:
    - job: Job1
      steps:
        - script: echo "##vso[task.setvariable variable=testKey;isOutput=true]True"
          name: value
        - script: echo $(value.testKey)
    - job: Job2
      dependsOn: Job1
      variables:
        testKey: $[dependencies.Job1.outputs['value.testKey']]
      steps:
        - script: echo $(testKey)
  - stage: Stage2
    dependsOn: Stage1
    jobs:
    - job: Job3
      dependsOn: Job1
      variables:
        testKey: $[dependencies.Job1.outputs['value.testKey']]
      steps:
        - script: echo $(testKey)