parameters:
  dependsOn: ''
  condition: ''

jobs:
- job: Build_Lib
  displayName: Lib
  dependsOn:
    ${{ if parameters.dependsOn }}
      - ${{ parameters.dependsOn }}
  condition:
    ${{ if parameters.condition }}
      - ${{ parameters.condition }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'build $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: '$(libProject)/*.csproj'
      arguments: '-c $(buildConfiguration)'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'libBinary'
      targetPath: '$(libBinaryDirectory)'