parameters:
  dependsOn: ''
  condition: 'succeeded()'

# must call template .azure-pipelines/build-lib.yml in before
jobs:
- job: Build_Core
  displayName: Core
  dependsOn:
    - Build_Lib
    - ${{ if parameters.dependsOn }}:
      - ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'libBinary'
      targetPath: '$(libBinaryDirectory)'
  - task: DotNetCoreCLI@2
    displayName: 'build $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: '$(coreProject)/*.csproj'
      arguments: '-c $(buildConfiguration)'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'coreBinary'
      targetPath: '$(coreBinaryDirectory)'